### ISSUE TITLE
ActionQueue: crash when everyone dies

### ISSUE THREAD

**Issue by saitou1024** [Fellowship-of-the-Bus/Draconia-Unity#140]
https://github.com/Fellowship-of-the-Bus/Draconia-Unity/blob/7cceda50cdfade2596100071bcac57000b3241d1/Assets/Script/UI/DataStructures/ActionQueue.cs#L58-L73

**Comment by Greatrabe** [comment]
fixed by 61721137a02674041f50c890be382f1c561d364b
