### ISSUE TITLE
movePiece is used improperly

### ISSUE THREAD

**Issue by saitou1024** [Fellowship-of-the-Bus/Draconia-Unity#22]
Refactor movePiece. Currently has too many bool arguments that are passed inconsistently. Also a second movePiece that should maybe have a different name.

**Comment by Greatrabe** [comment]
Fixed with https://github.com/Fellowship-of-the-Bus/Draconia-Unity/commit/035f348cd7abe8b5c9cc5dadf9578d8121b7ab6f
